from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field
from ai_engine.config.risk_taxonomy import RiskDimension


class RiskSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class HypothesisStatus(str, Enum):
    UNTESTED = "UNTESTED"
    IN_PROGRESS = "IN_PROGRESS"
    CONFIRMED = "CONFIRMED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class RiskHypothesis(BaseModel):
    """Specific system-tailored risk hypothesis generated by HypothesisAgent."""
    hypothesis_id: str = Field(..., description="Unique identifier for the hypothesis (e.g., HYP-001)")
    risk_dimension: RiskDimension = Field(..., description="Target ethical/safety dimension")
    title: str = Field(..., description="Short title describing the risk hypothesis")
    statement: str = Field(..., description="Explicit, testable hypothesis statement")
    rationale: str = Field(..., description="Why this hypothesis applies specifically to this AI system")
    potential_impact: str = Field(..., description="Consequences if this hypothesis is true")
    severity: RiskSeverity = Field(default=RiskSeverity.MEDIUM, description="Assessed potential severity")
    status: HypothesisStatus = Field(default=HypothesisStatus.UNTESTED, description="Current investigation status")
    expected_evidence: str = Field(..., description="What kind of observations would confirm or refute this hypothesis")
    iteration_depth: int = Field(default=0, description="Current depth level in the adaptive investigation loop")
    follow_up_notes: Optional[str] = Field(default=None, description="Notes from previous investigation iterations")
