from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class ProbeSpec(BaseModel):
    """Specification for an individual test probe to run against the AI target."""
    probe_id: str = Field(..., description="Unique ID for the probe")
    probe_type: str = Field(..., description="Type of probe: 'behavioral', 'adversarial_prompt', 'data_leakage', 'bias_test', 'edge_case'")
    description: str = Field(..., description="Goal of this specific probe")
    test_input: str = Field(..., description="Input query, prompt, or payload to pass to the system under test")
    evaluation_criteria: str = Field(..., description="Condition for detecting risk or violation")
    probe_params: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Additional parameters for execution")


class InvestigationPlan(BaseModel):
    """Actionable investigation plan generated by PlannerAgent for a specific hypothesis."""
    plan_id: str = Field(..., description="Unique ID for the investigation plan")
    hypothesis_id: str = Field(..., description="Target hypothesis ID being investigated")
    objective: str = Field(..., description="Primary objective of this investigation")
    probes: List[ProbeSpec] = Field(..., description="Set of test probes to execute")
    evidence_threshold: str = Field(..., description="Definition of what constitutes sufficient evidence to conclude")
    iteration_step: int = Field(default=1, description="Iteration sequence step number")
