from typing import List, Optional
from pydantic import BaseModel, Field
from ai_engine.models.hypothesis import RiskSeverity, HypothesisStatus
from ai_engine.config.risk_taxonomy import RiskDimension


class VerifiedRiskFinding(BaseModel):
    """Detailed verified risk item included in the final audit report."""
    finding_id: str
    risk_dimension: RiskDimension
    title: str
    severity: RiskSeverity
    hypothesis_statement: str
    evidence_summary: str
    impact_analysis: str
    recommended_mitigation: str
    confidence_score: float


class AuditReport(BaseModel):
    """Comprehensive final risk audit report generated by the AI Engine."""
    audit_id: str
    system_name: str
    audit_timestamp: str
    system_summary: str
    total_hypotheses_evaluated: int
    verified_findings: List[VerifiedRiskFinding] = Field(default_factory=list)
    refuted_hypotheses: List[str] = Field(default_factory=list, description="Titles of hypotheses that were tested and refuted")
    inconclusive_hypotheses: List[str] = Field(default_factory=list, description="Hypotheses where evidence remained inconclusive")
    overall_risk_rating: RiskSeverity = Field(..., description="Overall calculated risk rating for the system")
    executive_summary: str = Field(..., description="High-level narrative for stakeholders")
    actionable_recommendations: List[str] = Field(default_factory=list, description="Prioritized recommendations for remediation")
