"""Prompts package initialization."""
from app.prompts.system_understanding import SYSTEM_UNDERSTANDING_PROMPT, SYSTEM_UNDERSTANDING_SYSTEM_PROMPT
from app.prompts.hypothesis import HYPOTHESIS_PROMPT_TEMPLATE, HYPOTHESIS_SYSTEM_PROMPT
from app.prompts.investigation import INVESTIGATION_PROMPT_TEMPLATE, INVESTIGATION_SYSTEM_PROMPT
from app.prompts.interpretation import INTERPRETATION_PROMPT_TEMPLATE, INTERPRETATION_SYSTEM_PROMPT
from app.prompts.adaptive import (
    ADAPTIVE_DECISION_PROMPT_TEMPLATE,
    ADAPTIVE_DECISION_SYSTEM_PROMPT,
    NEXT_INVESTIGATION_PROMPT_TEMPLATE
)

__all__ = [
    "SYSTEM_UNDERSTANDING_PROMPT",
    "SYSTEM_UNDERSTANDING_SYSTEM_PROMPT",
    "HYPOTHESIS_PROMPT_TEMPLATE",
    "HYPOTHESIS_SYSTEM_PROMPT",
    "INVESTIGATION_PROMPT_TEMPLATE",
    "INVESTIGATION_SYSTEM_PROMPT",
    "INTERPRETATION_PROMPT_TEMPLATE",
    "INTERPRETATION_SYSTEM_PROMPT",
    "ADAPTIVE_DECISION_PROMPT_TEMPLATE",
    "ADAPTIVE_DECISION_SYSTEM_PROMPT",
    "NEXT_INVESTIGATION_PROMPT_TEMPLATE"
]
